#!/system/bin/sh
#
# resetting zram
echo 1 > /sys/block/zram0/reset
# setting zram size to 150MB
echo 157286400 > /sys/block/zram0/disksize
#
# making zram swapable
mkswap /dev/block/zram0
#
# starting swap on zram
swapon /dev/block/zram0
#
# setting swappiness to 30
echo 80 > /proc/sys/vm/swappiness
